CDH-31283 - NoClassDefFoundError: com/cloudera/io/netty/channel/EventLoopGroup
Introduce a ivy dependency for org.apache.hadoop.cloudera-netty-all module

Change-Id: I6ed100bc70a4c48db2cb806d5506235be99e8ba3
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/7991
Tested-by: jenkins
Reviewed-by: Greg Chanan <gchanan@cloudera.com>